version: '3'

volumes:
  uploads:

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        - GIT_COMMIT=095174e
    container_name: app
    ports:
      - "8088:8088"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - uploads:/usr/src/app/uploads

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - GIT_COMMIT=095174e
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env