version: '3'

volumes:
  data:

services:
  db:
    image: postgis/postgis:12-master
    container_name: db
    env_file:
      - .env
    volumes:
      - ./db/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
      - data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - GIT_COMMIT=adf512c
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env