version: '3'

volumes:
  data:

services:
  db:
    image: postgis/postgis:12-master
    container_name: db
    env_file:
      - .env
    volumes:
      - ./db/init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
      - data:/var/lib/postgresql/data

  redis:
    image: redis:6.0.1-alpine
    container_name: redis
    command: 
      --requirepass ${REDIS_PASSWORD}

  birdnet:
    build:
      context: .
      dockerfile: birdnet/Dockerfile
    container_name: birdnet
