version: '3'

volumes:
  uploads:

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
      args:
        - GIT_COMMIT=7e1651a
    container_name: app
    ports:
      - "8088:8088"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - uploads:/usr/src/app/uploads

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
      args:
        - GIT_COMMIT=2c4cc01
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
      args:
        - GIT_COMMIT=7e1651a
    container_name: worker
    depends_on: 
      - db
      - redis
    env_file:
      - .env